name: suezproduction
description: "قناة السويس للتأمين"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  # DateTime
  jiffy: ^5.0.0
  intl: ^0.18.1
  http: ^0.13.4
  # Images
  cached_network_image: ^3.2.0
  image_picker: ^0.8.7+1
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1


  # Google Map
  google_maps_flutter: ^2.1.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.4
    # Firebase And Notification
    #  firebase_messaging: any
    # firebase_core: any
    #flutter_local_notifications: any
    #cloud_firestore: any
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  badges: ^3.0.3
    # Icon
  # flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.0.2
  responsive_builder: ^0.7.0
  flutter_image_slideshow: ^0.1.6
  flutter_svg: ^2.0.4
  flutter_otp_text_field: ^1.0.1
  lottie: ^2.3.1
  flutter_html: any
  whatsapp_sender_flutter: ^0.2.0
  webview_flutter: ^4.7.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_splash_screen: ^3.0.0
  flutter_screenutil: ^5.9.0
  dio: ^4.0.6
  flutter_staggered_grid_view: ^0.4.1
  html_editor_enhanced: ^2.5.1
  quill_html_editor: ^2.1.9
  firebase_messaging: ^14.7.19
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_core: ^2.24.2
  shimmer:
  flutter_touch_ripple: ^1.1.21
  getwidget: ^4.0.0
  scrollable_list_tab_scroller: ^0.2.0
  pinch_zoom: ^2.0.0
  dropdown_button2: ^1.9.2
  local_auth: any
  flutter_secure_storage: ^9.2.2
  flutter_typeahead: ^4.1.0
  google_fonts: any
  empty_widget: ^0.0.3
  im_stepper: any
  form_field_validator: any
  dialog_flowtter: ^0.3.1
  multi_select_flutter: ^4.0.0
  mailto: ^2.0.0
  flutter_facebook_auth: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/dialogflow-435107-5dccaba2388d.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
